version: '3.8'
services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
      - ./database:/var/www/html/database  # Добавить эту строку
    networks:
      - app-network

  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./database:/var/www/html/database  # Добавить эту строку
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network: